--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.1.45.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 2019-05-15 21:41:59
-- Server version: 5.5.5-10.3.12-MariaDB
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO dsmr5.OBIS_reference(OBIS_ref, value, unit) VALUES
('0-0:1.0.0', 'Date-time stamp of the P1 message', 'YYMMDDhhmm'),
('0-0:96.1.1', 'Equipment identifier', NULL),
('0-0:96.13.0', 'Text message max 1024 characters.', NULL),
('0-0:96.14.0', 'Tariff indicator electricity. The tariff indicator can also be used to switch tariff dependent loads e.g boilers. This is the responsibility of the P1 user', NULL),
('0-0:96.7.21', 'Number of power failures in any phase', NULL),
('0-0:96.7.9', 'Number of long power failures in any phase', NULL),
('0-n:24.1.0', 'Device-Type', NULL),
('1-0:1.7.0', 'Actual electricity power delivered (+P) in 1 Watt resolution', 'kW'),
('1-0:1.8.1', 'Meter Reading electricity delivered to client (Tariff 1) in 0,001 kWh', 'kWh'),
('1-0:1.8.2', 'Meter Reading electricity delivered to client (Tariff 2) in 0,001 kWh', 'kWh'),
('1-0:2.7.0', 'Actual electricity power received (-P) in 1 Watt resolution', 'kW'),
('1-0:2.8.1', 'Meter Reading electricity delivered by client (Tariff 1) in 0,001 kWh', 'kWh'),
('1-0:2.8.2', 'Meter Reading electricity delivered by client (Tariff 2) in 0,001 kWh', 'kWh'),
('1-0:21.7.0', 'Instantaneous active power L1 (+P) in W resolution', 'kW'),
('1-0:22.7.0', 'Instantaneous active power L1 (-P) in W resolution', 'kW'),
('1-0:31.7.0', 'Instantaneous current L1 in A resolution.', 'A'),
('1-0:32.32.0', 'Number of voltage sags in phase L1', NULL),
('1-0:32.36.0', 'Number of voltage swells in phase L1', NULL),
('1-0:32.7.0', 'Instantaneous voltage L1 in V resolution', 'V'),
('1-0:41.7.0', 'Instantaneous active power L2 (+P) in W resolution', 'kW'),
('1-0:42.7.0', 'Instantaneous active power L2 (-P) in W resolution', 'kW'),
('1-0:51.7.0', 'Instantaneous current L2 in A resolution.', 'A'),
('1-0:52.32.0', 'Number of voltage sags in phase L2 ', NULL),
('1-0:52.36.0', 'Number of voltage swells in phase L2', NULL),
('1-0:52.7.0', 'Instantaneous voltage L2 in V resolution', 'V'),
('1-0:61.7.0', 'Instantaneous active power L3 (+P) in W resolution', 'kW'),
('1-0:62.7.0', 'Instantaneous active power L3 (-P) in W resolution', 'kW'),
('1-0:71.7.0', 'Instantaneous current L3 in A resolution.', 'A'),
('1-0:72.32.0', 'Number of voltage sags in phase L3', NULL),
('1-0:72.36.0', 'Number of voltage swells in phase L3', NULL),
('1-0:72.7.0', 'Instantaneous voltage L3 in V resolution', 'V'),
('1-0:99.97.0', 'Power Failure Event Log (long power failures)', NULL),
('1-3:0.2.8', 'Version information for P1 output', NULL);